// Zone 1 — Eastbrook Vale (levels 1-7). Data from src/sim/content/zone1.ts.
export const ZONE1 = {
  id: 'eastbrook_vale', name: 'Eastbrook Vale', levelRange: [1, 7], zRange: [-180, 180],
  graveyard: { x: -12, z: -14 }, hub: { x: 0, z: 0, name: 'Eastbrook' },
  foodVendor: { tid: 'trader_wilkes', x: -7, z: 3 },
  npcs: {
    marshal_redbrook: { x: 4, z: 6 }, trader_wilkes: { x: -7, z: 3 }, apothecary_lin: { x: 11, z: -3 },
    brother_aldric: { x: -14, z: -10 }, fisherman_brandt: { x: -16, z: 6 }, foreman_odell: { x: -4, z: -14 },
    smith_haldren: { x: 7, z: 16.5 }, the_merchant: { x: 0, z: 9.5 },
  },
  quests: {
    q_wolves:   { giver: 'marshal_redbrook', turnin: 'marshal_redbrook', objectives: [{ type: 'kill', targetMobId: 'forest_wolf', count: 8 }] },
    q_boars:    { giver: 'trader_wilkes', turnin: 'trader_wilkes', objectives: [{ type: 'collect', itemId: 'boar_hide', count: 5 }] },
    q_spiders:  { giver: 'apothecary_lin', turnin: 'apothecary_lin', minLevel: 2, objectives: [{ type: 'kill', targetMobId: 'webwood_spider', count: 6 }, { type: 'collect', itemId: 'webwood_silk', count: 4 }] },
    q_murlocs:  { giver: 'fisherman_brandt', turnin: 'fisherman_brandt', minLevel: 3, objectives: [{ type: 'kill', targetMobId: 'mudfin_murloc', count: 8 }] },
    q_supplies: { giver: 'trader_wilkes', turnin: 'trader_wilkes', minLevel: 3, objectives: [{ type: 'collect', itemId: 'supply_crate', count: 4 }] },
    q_mine:     { giver: 'foreman_odell', turnin: 'foreman_odell', minLevel: 4, objectives: [{ type: 'kill', targetMobId: 'tunnel_rat', count: 10 }] },
    q_bones:    { giver: 'brother_aldric', turnin: 'brother_aldric', minLevel: 5, objectives: [{ type: 'kill', targetMobId: 'restless_bones', count: 8 }] },
    q_whispers: { giver: 'brother_aldric', turnin: 'brother_aldric', requiresQuest: 'q_bones', objectives: [{ type: 'collect', itemId: 'gravecaller_sigil', count: 1 }] },
    q_names_of_the_dead: { giver: 'brother_aldric', turnin: 'brother_aldric', requiresQuest: 'q_whispers', objectives: [{ type: 'collect', itemId: 'weathered_ledger_page', count: 3 }] },
    q_silence_the_call:  { giver: 'brother_aldric', turnin: 'brother_aldric', requiresQuest: 'q_names_of_the_dead', objectives: [{ type: 'kill', targetMobId: 'restless_bones', count: 12 }] },
    q_rite:     { giver: 'brother_aldric', turnin: 'brother_aldric', requiresQuest: 'q_whispers', objectives: [{ type: 'collect', itemId: 'blessed_wax', count: 4 }, { type: 'collect', itemId: 'ghostly_essence', count: 6 }] },
    q_bandits:  { giver: 'marshal_redbrook', turnin: 'marshal_redbrook', requiresQuest: 'q_wolves', objectives: [{ type: 'kill', targetMobId: 'vale_bandit', count: 10 }] },
  },
  questOrder: ['q_wolves', 'q_boars', 'q_spiders', 'q_murlocs', 'q_supplies', 'q_mine', 'q_bandits', 'q_bones', 'q_whispers', 'q_names_of_the_dead', 'q_silence_the_call', 'q_rite'],
  camps: [
    { mobId: 'forest_wolf', x: -15, z: 55, radius: 22, minLevel: 1, maxLevel: 2 },
    { mobId: 'forest_wolf', x: 20, z: 70, radius: 20, minLevel: 1, maxLevel: 2 },
    { mobId: 'wild_boar', x: 55, z: 12, radius: 22, minLevel: 2, maxLevel: 3 },
    { mobId: 'wild_boar', x: 80, z: -15, radius: 18, minLevel: 2, maxLevel: 3 },
    { mobId: 'webwood_spider', x: -60, z: 5, radius: 22, minLevel: 2, maxLevel: 4 },
    { mobId: 'mudfin_murloc', x: -75, z: 57, radius: 14, minLevel: 3, maxLevel: 5 },
    { mobId: 'vale_bandit', x: 65, z: -65, radius: 24, minLevel: 3, maxLevel: 5 },
    { mobId: 'vale_bandit', x: 90, z: -90, radius: 16, minLevel: 3, maxLevel: 5 },
    { mobId: 'tunnel_rat', x: -82, z: -62, radius: 20, minLevel: 4, maxLevel: 6 },
    { mobId: 'restless_bones', x: 80, z: 78, radius: 18, minLevel: 5, maxLevel: 7 },
    { mobId: 'old_greyjaw', x: 0, z: 95, radius: 8, minLevel: 4, maxLevel: 4, dangerous: true },
    { mobId: 'elder_bristleback', x: 104, z: 24, radius: 4, minLevel: 5, maxLevel: 5, dangerous: true },
    { mobId: 'sableweb_matriarch', x: -72, z: 28, radius: 5, minLevel: 6, maxLevel: 6, dangerous: true },
    { mobId: 'mogger', x: 118, z: -26, radius: 5, minLevel: 6, maxLevel: 6, dangerous: true },
    { mobId: 'gorrak', x: 92, z: -92, radius: 2, minLevel: 6, maxLevel: 6, dangerous: true },
  ],
  ground: {
    supply_crate: [{ x: 58, z: -58 }, { x: 73, z: -70 }, { x: 86, z: -82 }, { x: 95, z: -97 }, { x: 64, z: -76 }, { x: 81, z: -94 }],
    gravecaller_sigil: [{ x: 84, z: 88 }, { x: 76, z: 92 }],
    weathered_ledger_page: [{ x: 78, z: 84 }, { x: 83, z: 88 }, { x: 86, z: 92 }],
  },
  itemSource: { boar_hide: 'wild_boar', webwood_silk: 'webwood_spider', blessed_wax: 'tunnel_rat', ghostly_essence: 'restless_bones' },
};
